name: Check disclosures 

on: 
  pull_request:
    branches:
      - master
      - staging
    paths:
      - 'bounties/**/vulnerability.json'

jobs:
  run-validator:
    name: 'JSON Validation'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/check-disclosures
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: tools/check-disclosures/assets/schemas/vulnerability.json
          INPUT_JSONS: bounties/**/vulnerability.json