name: Disclosure Submitted
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - action/disclosure-submitted
    paths:
      - "bounties/**"

defaults:
  run:
    working-directory: tools/disclosure-submitted

jobs:
  generate-diff:
    name: Generate diff
    runs-on: ubuntu-latest
    outputs: 
      diff: ${{ steps.generate-diff.outputs.diff }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.number }}/merge
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install NPM packages
        run: npm ci
      - id: generate-diff
        name: Generate diff
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: node ./generate-diff.js
  contains-only-new-files:
    name: Check for only new files
    needs: generate-diff
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install NPM packages
        run: npm ci
      - id: contains-only-new-files
        name: Check for only new files
        env:
          DIFF: ${{ needs.generate-diff.outputs.diff }}
        run: node ./contains-only-new-files.js
  contains-only-one-directory:
    name: Contains only one directory
    needs: generate-diff
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install npm dependencies
        run: npm ci
      - id: contains-only-one-directory
        name: Contains only one directory
        env:
          DIFF: ${{ needs.generate-diff.outputs.diff }}
        run: node ./contains-only-one-directory.js
  contains-only-db-files:
    name: Contains only database files
    needs: generate-diff
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install NPM packages
        run: npm ci
      - id: contains-only-db-files
        name: Contains only database files
        env:
          DIFF: ${{ needs.generate-diff.outputs.diff }}
        run: node ./contains-only-db-files.js
  contains-a-valid-directory:
    name: Contains a valid directory
    needs: generate-diff
    outputs: 
      package-name: ${{ steps.contains-a-valid-directory.outputs.package-name }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install NPM packages
        run: npm ci
      - id: contains-a-valid-directory
        name: Contains a valid directory
        env:
          DIFF: ${{ needs.generate-diff.outputs.diff }}
        run: node ./contains-a-valid-directory.js
  contains-a-readme:
    name: Contains a README
    needs: generate-diff
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install NPM packages
        run: npm ci
      - id: contains-a-readme
        name: Contains a README
        env:
          DIFF: ${{ needs.generate-diff.outputs.diff }}
        run: node ./contains-a-readme.js
  contains-a-valid-json:
    name: Contains a valid JSON
    needs: generate-diff
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install NPM packages
        run: npm ci
      - id: contains-a-valid-json
        name: Contains a valid JSON
        env:
          DIFF: ${{ needs.generate-diff.outputs.diff }}
        run: node ./contains-a-valid-json.js
  contains-a-valid-repo:
    name: Contains a valid repo
    needs: generate-diff
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install NPM packages
        run: npm ci
      - id: contains-a-valid-repo
        name: Contains a valid repo
        env:
          DIFF: ${{ needs.generate-diff.outputs.diff }}
        run: node ./contains-a-valid-json.js
  contains-relevant-package-info:
    name: Contains relevant package information
    needs: generate-diff
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install NPM packages
        run: npm ci
      - id: contains-a-related-repo
        name: Contains relevant package information
        env:
          DIFF: ${{ needs.generate-diff.outputs.diff }}
          GRAPHQL_API_URL: ${{ secrets.GRAPHQL_API_URL }}
          GRAPHQL_API_KEY: ${{ secrets.GRAPHQL_API_KEY }}
        run: node ./contains-relevant-package-info.js
  add-label:
    name: Add label to PR
    needs: [
      contains-only-new-files,
      contains-only-one-directory,
      contains-only-db-files,
      contains-a-valid-directory,
      contains-a-readme,
      contains-a-valid-json,
      contains-a-valid-repo,
      contains-relevant-package-info
    ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.github_token }}
          labels: disclosure
  analytics:
    name: Run Heap Analytics
    runs-on: ubuntu-latest
    needs: [
      contains-a-read-me,
      contains-only-new-files,
      contains-only-db-files,
      contains-only-one-directory
    ]
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install NPM packages
        run: npm ci
      - id: analytics
        name: Run Heap Analytics
        env:
          HEAP_ID: "${{ secrets.HEAP_ID }}"
          EVENT_NAME: "Disclosure Submitted"
          USER_ID: ${{ github.event.pull_request.user.id }}
          PACKAGE_NAME: ${{ needs.contains-a-valid-directory.outputs.package-name }}
        run: node ../shared/analytics.js
  # auto-merge:
  #   name: Auto merge PR
  #   runs-on: ubuntu-latest
  #   needs: add-label
  #   steps:
  #     - name: Auto merge PR
  #       uses: "pascalgn/automerge-action@v0.13.0"
  #       env:
  #         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  #         MERGE_LABELS: "disclosure"
